# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Published')], max_length=10, verbose_name='文章状态'),
        ),
    ]
